version: "3.9"
services:
  api:
    build: ./backend
    container_name: api
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app:rw
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app:rw
    ports:
      - "5173:5173"
    command: npm run dev -- --host

  # Uncomment to switch to PostgreSQL
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
